config/routes.rb
Rails.application.routes.draw do
  resources :encounters

  resources :items

  resources :occupations

  resources :actions

  resources :buildings

  resources :characters do
    get :random
  end

  resources :locations

  resources :games do
    get :next_event, on: :member
  end

  devise_for :users

  root to: 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user

  has_many :locations

  has_many :encounters, through: :locations do
  end

  has_many :characters do
    def available
      where('location_id IS NULL')
    end

    def pcs
      where(is_pc: true)
    end

    def npcs
      where(is_pc: false)
    end
  end

  def setup!
    set_time!
    generate_characters!
    generate_locations!
    generate_encounters!
  end

  def move!(character, position, action_name)
    result = current_location.move!(character, position, action_name)

    if result && result[:time]
      update_attributes!(
        time: result[:time],
        prior_action_at: time
      )
    end
  end

  def recent_moves
    current_location.moves.since(prior_action_at)
  end

  def current_location
    locations.where(is_current: true).first
  end

  HELLRAISER_RELEASE_DATE = 'September 18, 1987'
  def set_time!
    update_attributes!(time: Time.parse(HELLRAISER_RELEASE_DATE))
  end

  def generate_characters!
    4.times do
      self.characters << Characters::Human.generate_pc!
    end
  end

  def police_station
    locations.where(type: Locations::PoliceStation).first
  end

  def hospital
    locations.where(type: Locations::Hospital).first
  end

  def generate_locations!
    Location.st_types.each do |_type|
      _type.generate!(self)
    end
  end

  def current_location!
    locations.sample.update_attributes!(is_current: true)
    current_location.spawn_group(characters)
    current_location.reload
  end

  def generate_encounters!
    l = locations.sample
    Encounter.generate_at! l if l
  end

  def wait_until_next!
    if encounters.incomplete.empty?
      generate_encounters!
      new_time = encounters.incomplete.order(:starts_at).first.starts_at
      update_attributes!(time: new_time)
    end
  end

  def json_map
    if current_location
      current_location.json_map
    else
      {}
    end
  end

  # move to location json
  def max_x
    current_location.max_x
  end

  # move to location json
  def max_y
    current_location.max_y
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_game, only: [:next_event, :show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @games = Game.all
    respond_with(@games)
  end

  def show
    respond_to do |format|
      format.html { @game }
      format.json { @game }
    end
  end

  def next_event
    @game.wait_until_next!
    redirect_to(@game)
  end

  def new
    @game = Game.new
    respond_with(@game)
  end

  def edit
  end

  def create
    @game = Game.new(game_params)
    @game.user = current_user
    @game.save
    @game.setup!
    respond_with(@game)
  end

  def update
    character = Character.find params['character_id']

    tci = params['target_character_id']
    if tci && Character.find(tci)
      character.update_attributes!(target_character_id: tci)
    end

    tii = params['target_item_id']
    if tii && Item.find(tii)
      character.update_attributes!(target_item_id: tii)
    end

    if character.can?(params['game_action'])
      position = [params['x'], params['y'], params['z']].map(&:to_i)
      @game.move!(character, position, params['game_action'])
    else
      raise "#{character.name} can't #{params['game_action']}!"
    end

    respond_to do |format|
      format.html { @game }
      format.json { @game }
    end
  end

  def destroy
    @game.destroy
    respond_with(@game)
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params[:game]
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.haml
%strong
  = @game.time

- if @game.current_location
  - cl = @game.current_location
  %strong
    = cl.display_name
  - cl.encounters.each do |e|
    = render 'encounters/encounter', encounter: e

  = form_for(@game.current_location.becomes(Location)) do |f|
    = f.hidden_field :is_current, value: false
    = f.submit "Leave Location"
  %p
    PCS
  - @game.current_location.characters.pcs.each do |c|
    = render 'characters/character', character: c
  %p
    NPCS
  - @game.current_location.characters.npcs.each do |c|
    = render 'characters/character', character: c

  .location_map{:data => {'game-id' => @game.id}}
- else
  %p
    = link_to 'WAIT', next_event_game_path(@game)

  %h1 Locations
  - @game.locations.each do |l|
    = render 'locations/location', location: l

  %h1 Available Characters
  - @game.characters.available.pcs.each do |c|
    = render 'characters/character', character: c
    = form_for(c.becomes(Character)) do |f|
      - # = f.text_field :name
      = f.select :location_id, @game.locations.collect {|p| [ p.display_name, p.id ] }, { include_blank: true }
      = f.submit