config/routes.rb
Rails.application.routes.draw do
  resources :encounters

  resources :items

  resources :occupations

  resources :actions

  resources :buildings

  resources :characters do
    get :random
  end

  resources :locations

  resources :games do
    get :next_event, on: :member
  end

  devise_for :users

  root to: 'games#index'

end

app/models/building.rb
require 'astrid'

class Building < ActiveRecord::Base
  belongs_to :location

  def grid
    if positioned?
      x, y = bottom_left_x, bottom_left_y

      grid_rep.inject({}) do |acc, kv|
        if kv.first.is_a? Array
          new_x = kv.first.first + x
          new_y = kv.first.second + y
          acc[[new_x, new_y]] = kv.second
        else
          acc[kv.first] = kv.second
        end
        acc
      end
    else
      grid_rep
    end
  end

  def positioned?
    bottom_left_x && bottom_left_y
  end

  def grid_rep
    Astrid::Finders::AStar.new.grid_from_s_map(<<-G)
._________.
.|.......|.
.........|.
.|.......|.
._________.
    G
  end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @buildings = Building.all
    respond_with(@buildings)
  end

  def show
    respond_with(@building)
  end

  def new
    @building = Building.new
    respond_with(@building)
  end

  def edit
  end

  def create
    @building = Building.new(building_params)
    @building.save
    respond_with(@building)
  end

  def update
    @building.update(building_params)
    respond_with(@building)
  end

  def destroy
    @building.destroy
    respond_with(@building)
  end

  private
    def set_building
      @building = Building.find(params[:id])
    end

    def building_params
      params.require(:building).permit(:name, :location_id)
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form.html.erb
<%= form_for(@building) do |f| %>
  <% if @building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% @building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.text_field :location_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing building</h1>

<%= render 'form' %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<h1>Listing buildings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buildings.each do |building| %>
      <tr>
        <td><%= building.name %></td>
        <td><%= building.location %></td>
        <td><%= link_to 'Show', building %></td>
        <td><%= link_to 'Edit', edit_building_path(building) %></td>
        <td><%= link_to 'Destroy', building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Building', new_building_path %>

app/views/buildings/new.html.erb
<h1>New building</h1>

<%= render 'form' %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @building.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @building.location %>
</p>

<%= link_to 'Edit', edit_building_path(@building) %> |
<%= link_to 'Back', buildings_path %>